"""The daily digest: due-soon commitments, pending calendar suggestions, and
how much new mail arrived - generated by a scheduled background job and
surfaced in-app (`GET /digest/latest`), not emailed.

That's a scope decision, not a shortcut: emailing it would need a new
`gmail.send` (or `gmail.compose`) OAuth scope on top of the existing
readonly + calendar.events, which means every existing tester re-consents,
adds real send-side risk (deliverability, rate limits, mailing the wrong
address), and can't be exercised in tests without live credentials. None of
that buys anything an in-app panel doesn't already give a signed-in user.
"""
from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import pyarrow.parquet as pq

from ..ingestion.worker import messages_path
from ..users import get_timezone

# How far ahead a digest looks for due commitments. A week matches the
# cadence a daily digest is actually useful at - far enough to plan around,
# not so far the list is just "everything with a date".
LOOKAHEAD_DAYS = 7


def _due_soon(conn, user_id: str) -> list[dict]:
    # `date.today()` (the obvious call here) is the *server's* local date,
    # which on a real deployment is whatever the host happens to be set to -
    # not this user's day. Same bug and same fix as chat/routes.py's `as_of`.
    try:
        tz = ZoneInfo(get_timezone(conn, user_id))
    except ZoneInfoNotFoundError:
        tz = timezone.utc
    today = datetime.now(tz).date()
    rows = conn.execute(
        "SELECT text, due_at, owner, counterparty FROM commitments "
        "WHERE user_id = %s AND due_at BETWEEN %s AND %s ORDER BY due_at",
        (user_id, today, today + timedelta(days=LOOKAHEAD_DAYS))).fetchall()
    return [{"text": r[0], "due_at": r[1].isoformat(), "owner": r[2], "counterparty": r[3]}
           for r in rows]


def _new_message_count(settings, user_id: str, since) -> int:
    msg_path = messages_path(settings.user_index_root, user_id)
    if not msg_path.exists():
        return 0
    dates = pq.read_table(msg_path, columns=["date_utc"]).column("date_utc").to_pylist()
    return sum(1 for d in dates if d is not None and d >= since)


def generate_digest(conn, settings, user_id: str) -> dict:
    """Compute and store one digest for `user_id`, returning its content.

    "New mail" is counted since the *previous* digest, falling back to the
    last 24h for a user's first one - there is nothing earlier to measure
    from yet.
    """
    from datetime import datetime, timezone

    last = conn.execute(
        "SELECT created_at FROM digests WHERE user_id = %s "
        "ORDER BY created_at DESC LIMIT 1", (user_id,)).fetchone()
    since = last[0] if last else (datetime.now(timezone.utc) - timedelta(days=1))

    pending = conn.execute(
        "SELECT count(*) FROM calendar_suggestions "
        "WHERE user_id = %s AND status = 'pending'", (user_id,)).fetchone()[0]

    content = {
        "due_soon": _due_soon(conn, user_id),
        "pending_calendar_suggestions": pending,
        "new_messages": _new_message_count(settings, user_id, since),
    }

    row = conn.execute(
        "INSERT INTO digests (user_id, content) VALUES (%s, %s) RETURNING id, created_at",
        (user_id, json.dumps(content))).fetchone()
    return {"id": str(row[0]), "created_at": row[1].isoformat(), **content}


def get_settings_row(conn, user_id: str) -> dict:
    row = conn.execute(
        "SELECT enabled, send_hour_utc, last_sent_utc FROM digest_settings "
        "WHERE user_id = %s", (user_id,)).fetchone()
    if row is None:
        return {"enabled": False, "send_hour_utc": 13, "last_sent_utc": None}
    return {"enabled": row[0], "send_hour_utc": row[1],
            "last_sent_utc": row[2].isoformat() if row[2] else None}


def save_settings(conn, user_id: str, enabled: bool, send_hour_utc: int) -> None:
    conn.execute(
        """
        INSERT INTO digest_settings (user_id, enabled, send_hour_utc)
        VALUES (%s, %s, %s)
        ON CONFLICT (user_id) DO UPDATE SET
            enabled = EXCLUDED.enabled, send_hour_utc = EXCLUDED.send_hour_utc
        """,
        (user_id, enabled, send_hour_utc))


def get_latest(conn, user_id: str) -> dict | None:
    row = conn.execute(
        "SELECT id, content, created_at FROM digests WHERE user_id = %s "
        "ORDER BY created_at DESC LIMIT 1", (user_id,)).fetchone()
    if row is None:
        return None
    return {"id": str(row[0]), "created_at": row[2].isoformat(), **row[1]}


def due_users(conn) -> list[str]:
    """Users whose digest is due right now: enabled, the current UTC hour
    matches their chosen send hour, and they haven't gotten one yet today.
    """
    rows = conn.execute(
        """
        SELECT user_id FROM digest_settings
        WHERE enabled
          AND send_hour_utc = extract(hour from now() at time zone 'utc')
          AND (last_sent_utc IS NULL
               OR (last_sent_utc at time zone 'utc')::date
                  < (now() at time zone 'utc')::date)
        """
    ).fetchall()
    return [str(r[0]) for r in rows]


def schedule_due_digests(conn) -> list[str]:
    """Enqueue a `generate_digest` job for every user whose digest is due,
    marking each as sent immediately so the next poll (seconds later)
    doesn't enqueue it again.

    That marking is optimistic: a digest that then fails is missed for the
    day rather than retried - the same bounded-effort trade-off `jobs.fail`
    already makes for every job type after its retries run out, just
    resolved up front here instead of after three attempts.
    """
    from ..jobs.queue import enqueue

    user_ids = due_users(conn)
    for user_id in user_ids:
        enqueue(conn, "generate_digest", user_id=user_id)
        conn.execute(
            "UPDATE digest_settings SET last_sent_utc = now() WHERE user_id = %s",
            (user_id,))
    return user_ids
